// Generated by https://quicktype.io

export interface CurrentLocation {
    coords:    Coords;
    mocked:    boolean;
    timestamp: number;
}

export interface Coords {
    latitude: number;
    longitude: number;
    altitude: number | null;
    accuracy: number;
    altitudeAccuracy: number | null;
    heading: number | null;
    speed: number | null;
}
